# server configuration
system:
  appName: ProxyPool
  configFile: conf/config.yaml
  # service listening address
  httpAddr: 0.0.0.0
  # service listening port
  httpPort: 3000
  # Session expires time
  sessionExpires: 168h0m0s

# mysql
database:
  dbType: mysql
  host: 127.0.0.1
  port: 3306
  dbName: test
  username: root
  password: root
  prefix: proxy_
  charset: utf8mb4
  parseTime: true
  maxIdleConns: 5
  maxOpenConns: 100
  # For "postgres" only, either "disable", "require" or "verify-full"
  sslMode: disable
  # For "sqlite3" and "tidb", use absolute path when you start as service
  path: data/ProxyPool.db

# logger configuration
log:
  filePath: logs
  fileName: run.log
  # Either "Trace", "Info", "Warn", "Error", "Fatal", default is "Trace"
  level: debug
  # Can be "console" and "file", default is "console"
  # Use comma to separate multiple modes, e.g. "console, file"
  mode: file
  file:
    # Segment log daily
    dailyRotate: true
    # Max size shift of single file, default is 28 means 1 << 28, 256MB
    maxSizeShift: 28
    # Max line number of single file
    maxLines: 1000000
    # Expired days of log file (delete after max days)
    maxDays: 7
  # Buffer length of channel, keep it as it is if you don't know what it is.
  bufferLen: 100
  # Root path of log files, align will fill it automatically.
  rootPath: ./logs

security:
  installLock = true